image: ruby

cache:
  paths:
    - gems

pages:
  script:
    - apt-get update -yqqq
    - apt-get install -y nodejs
    - npm install -g bower
    - bundle install --path=gems
    - npm install -g bower vulcanize
    - bundle exec rake site
  artifacts:
    paths:
      - build
  only:
    - master
