image: ruby:2.4

cache:
  paths:
    - gems

pages:
  cache:
    paths:
      - gems/
      - node_modules/
      - source/bower_components/
  script:
    - apt-get update -yqqq
    - curl -sL https://deb.nodesource.com/setup_6.x | bash -
    - apt-get install -y nodejs
    - npm install bower vulcanize
    - bundle install --path=gems
    - $(npm bin)/bower install
    - RUBYOPT=-EUTF-8 bundle exec rake site
  artifacts:
    paths:
      - build
  only:
    - master
