image: ruby:2.4

cache:
  paths:
    - gems

pages:
  script:
    - apt-get update -yqqq
    - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    - apt-get install -y nodejs
    - npm install -g bower vulcanize
    - bundle install --path=gems
    - bundle exec rake site
  artifacts:
    paths:
      - build
  only:
    - master
