image: ruby:2.4

cache:
  paths:
    - gems

pages:
  cache:
    paths:
      - gems/
      - node_modules/
      - source/bower_components/
  script:
    - apt-get update -yqqq
    - curl -sL https://deb.nodesource.com/setup_6.x | bash -
    - apt-get install -y nodejs
    - npm install -g bower vulcanize
    - bundle install --path=gems
    - bower install --allow-root
    - RUBYOPT=-EUTF-8 bundle exec rake site
    - mkdir .public
    - mv build/* .public/
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
